// Local in-memory lookup over the SDE blueprint data generated by
// src/buildSde.js (see `sde:build` in package.json, run as a predev/prebuild
// step). Covers manufacturing and reaction blueprints — the "consume
// materials → produce output" activities — so the app can answer "how do I
// build X" and "what consumes X" without a DB round trip or ESI call. Loaded
// once per server process and reused across requests. Mirrors src/sdeTypes.ts.
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

// EVE industry activity ids present in the generated data.
export const MANUFACTURING = 1
export const REACTION = 11

export type BlueprintMaterial = { typeID: number; quantity: number }
export type Blueprint = {
  blueprintTypeID: number
  activityID: number
  productTypeID: number
  productQuantity: number
  materials: BlueprintMaterial[]
}

type SdeTuple = [
  blueprintTypeID: number,
  activityID: number,
  productTypeID: number,
  productQuantity: number,
  materials: [typeID: number, quantity: number][],
]

let blueprints: Blueprint[] | null = null
let byProduct: Map<number, Blueprint[]> | null = null
let byMaterial: Map<number, Blueprint[]> | null = null

const index = (map: Map<number, Blueprint[]>, id: number, bp: Blueprint) => {
  const list = map.get(id) ?? []
  list.push(bp)
  map.set(id, list)
}

const load = (): Blueprint[] => {
  if (blueprints) return blueprints
  const path = join(process.cwd(), 'src', 'generated', 'sdeBlueprints.json')
  const tuples = JSON.parse(readFileSync(path, 'utf8')) as SdeTuple[]
  blueprints = tuples.map(([blueprintTypeID, activityID, productTypeID, productQuantity, materials]) => ({
    blueprintTypeID,
    activityID,
    productTypeID,
    productQuantity,
    materials: materials.map(([typeID, quantity]) => ({ typeID, quantity })),
  }))
  byProduct = new Map()
  byMaterial = new Map()
  for (const bp of blueprints) {
    index(byProduct, bp.productTypeID, bp)
    for (const m of bp.materials) index(byMaterial, m.typeID, bp)
  }
  return blueprints
}

// The blueprint that produces the given product. Manufacturing is preferred
// over a reaction when a product is somehow made by both, and lower blueprint
// type id breaks any remaining tie — so the choice is stable across builds.
export const getBlueprintForProduct = (productTypeID: number): Blueprint | null => {
  load()
  const candidates = byProduct?.get(productTypeID) ?? []
  if (candidates.length === 0) return null
  return [...candidates].sort(
    (a, b) =>
      Number(b.activityID === MANUFACTURING) - Number(a.activityID === MANUFACTURING) ||
      a.blueprintTypeID - b.blueprintTypeID
  )[0]
}

// Every blueprint that consumes the given type as an input material, ordered
// by product type id for a stable, browsable result.
export const getBlueprintsForMaterial = (materialTypeID: number): Blueprint[] => {
  load()
  return [...(byMaterial?.get(materialTypeID) ?? [])].sort((a, b) => a.productTypeID - b.productTypeID)
}
