// Local in-memory lookup over the SDE planet data generated by src/buildSde.js
// (see `sde:build` in package.json, run as a predev/prebuild step). Lets the app
// resolve a planet's solar system, celestial index, type, and derived display
// name without calling ESI — loaded once per server process and reused across
// requests. Mirrors src/sdeSystems.ts. The SDE stores no planet name (EVE
// derives it as "<system> <roman(celestialIndex)>"), so `name`/`roman` are
// reconstructed here from the system name (via sdeSystems) + celestial index.
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { getSdeSystem } from './sdeSystems'

// Temperate planet type — the planet type mercenary dens deploy to.
export const TEMPERATE_PLANET_TYPE_ID = 11

export type SdePlanet = {
  planetID: number
  systemID: number
  systemName: string | null
  celestialIndex: number | null
  typeID: number | null
  roman: string | null
  name: string
}

type SdeTuple = [planetID: number, systemID: number, celestialIndex: number | null, typeID: number | null]

let byID: Map<number, SdeTuple> | null = null

const load = (): Map<number, SdeTuple> => {
  if (byID) return byID
  const path = join(process.cwd(), 'src', 'generated', 'sdePlanets.json')
  const tuples = JSON.parse(readFileSync(path, 'utf8')) as SdeTuple[]
  byID = new Map(tuples.map((t) => [t[0], t]))
  return byID
}

// Roman numeral for a planet's celestial index (1 → "I", 4 → "IV", …). EVE
// planet indices never get large, but this handles any positive integer.
export const toRoman = (n: number): string => {
  if (!Number.isInteger(n) || n <= 0) return String(n)
  const table: [number, string][] = [
    [1000, 'M'],
    [900, 'CM'],
    [500, 'D'],
    [400, 'CD'],
    [100, 'C'],
    [90, 'XC'],
    [50, 'L'],
    [40, 'XL'],
    [10, 'X'],
    [9, 'IX'],
    [5, 'V'],
    [4, 'IV'],
    [1, 'I'],
  ]
  let remaining = n
  let out = ''
  for (const [value, numeral] of table) {
    while (remaining >= value) {
      out += numeral
      remaining -= value
    }
  }
  return out
}

export const getSdePlanet = (planetID: number): SdePlanet | null => {
  const tuple = load().get(planetID)
  if (!tuple) return null
  const [, systemID, celestialIndex, typeID] = tuple
  const roman = celestialIndex != null ? toRoman(celestialIndex) : null
  const systemName = getSdeSystem(systemID)?.name ?? null
  const name = systemName ? `${systemName}${roman ? ` ${roman}` : ''}` : `Planet #${planetID}`
  return { planetID, systemID, systemName, celestialIndex, typeID, roman, name }
}

export const getSdePlanets = (planetIDs: Iterable<number>): Record<number, SdePlanet> => {
  const out: Record<number, SdePlanet> = {}
  for (const id of planetIDs) {
    const planet = getSdePlanet(id)
    if (planet) out[id] = planet
  }
  return out
}
