// Local in-memory lookup over the SDE NPC-station data generated by
// src/buildSde.js (see `sde:build` in package.json, run as a predev/prebuild
// step). Lets the app resolve station names and their solar system without
// calling ESI or a DB round trip — loaded once per server process and reused
// across requests. Mirrors src/sdeSystems.ts for solar-system data.
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fromPairs, reduce } from 'ramda'

export type SdeStation = { stationID: number; name: string; systemID: number }
type SdeTuple = [stationID: number, name: string, systemID: number]

let stations: SdeStation[] | null = null
let byID: Map<number, SdeStation> | null = null

const load = (): SdeStation[] => {
  if (stations) return stations
  const path = join(process.cwd(), 'src', 'generated', 'sdeStations.json')
  const tuples = JSON.parse(readFileSync(path, 'utf8')) as SdeTuple[]
  stations = tuples.map(([stationID, name, systemID]) => ({ stationID, name, systemID }))
  byID = new Map(stations.map((s) => [s.stationID, s]))
  return stations
}

export const getSdeStation = (stationID: number): SdeStation | null => {
  load()
  return byID?.get(stationID) ?? null
}

const resolvedPairs = <T>(stationIDs: Iterable<number>, pick: (s: SdeStation) => T): [number, T][] =>
  reduce(
    (acc: [number, T][], id: number) => {
      const station = getSdeStation(id)
      if (station) acc.push([id, pick(station)])
      return acc
    },
    [],
    [...stationIDs]
  )

export const getSdeStationNames = (stationIDs: Iterable<number>): Record<number, string> =>
  fromPairs(resolvedPairs(stationIDs, (s) => s.name))

export const getSdeStationSystems = (stationIDs: Iterable<number>): Record<number, number> =>
  fromPairs(resolvedPairs(stationIDs, (s) => s.systemID))
