// Local in-memory lookup over the SDE solar-system data generated by
// src/buildSde.js (see `sde:build` in package.json, run as a predev/prebuild
// step). Lets the app resolve system names and search systems by name without
// calling ESI — loaded once per server process and reused across requests.
// Mirrors src/sdeTypes.ts for type data.
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

export type SdeSystem = { systemID: number; name: string; security: number }
type SdeTuple = [systemID: number, name: string, security: number]

let systems: SdeSystem[] | null = null
let byID: Map<number, SdeSystem> | null = null

const load = (): SdeSystem[] => {
  if (systems) return systems
  const path = join(process.cwd(), 'src', 'generated', 'sdeSystems.json')
  const tuples = JSON.parse(readFileSync(path, 'utf8')) as SdeTuple[]
  systems = tuples.map(([systemID, name, security]) => ({ systemID, name, security }))
  byID = new Map(systems.map((s) => [s.systemID, s]))
  return systems
}

export const getSdeSystem = (systemID: number): SdeSystem | null => {
  load()
  return byID?.get(systemID) ?? null
}

export const getSdeSystemNames = (systemIDs: Iterable<number>): Record<number, string> => {
  const result: Record<number, string> = {}
  for (const id of systemIDs) {
    const system = getSdeSystem(id)
    if (system) result[id] = system.name
  }
  return result
}

// EVE shows a system's security status rounded to one decimal.
export const formatSecurity = (security: number): string => security.toFixed(1)

export type SdeSystemSearchResult = SdeSystem & { coverage: number }

// Case-insensitive substring search, ranked by how much of the name the query
// covers (a tighter match ranks above a longer name containing the same term).
// Mirrors searchSdeTypes.
export const searchSdeSystems = (query: string, limit = 25): SdeSystemSearchResult[] => {
  const needle = query.trim().toLowerCase()
  if (needle === '') return []
  const results: SdeSystemSearchResult[] = []
  for (const s of load()) {
    const idx = s.name.toLowerCase().indexOf(needle)
    if (idx === -1) continue
    results.push({ ...s, coverage: needle.length / s.name.length })
  }
  results.sort((a, b) => b.coverage - a.coverage || a.name.length - b.name.length)
  return results.slice(0, limit)
}
