// Local in-memory lookup over the SDE type data generated by src/buildSde.js
// (see `sde:build` in package.json, run as a predev/prebuild step). Replaces
// the old runtime dependency on sde.edencom.link with data baked in at build
// time — loaded once per server process and reused across requests.
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

type SdeType = { typeID: number; name: string; groupID: number; categoryID: number | null }
type SdeTuple = [typeID: number, name: string, groupID: number, categoryID: number | null]

let types: SdeType[] | null = null
let byID: Map<number, SdeType> | null = null

const load = (): SdeType[] => {
  if (types) return types
  const path = join(process.cwd(), 'src', 'generated', 'sdeTypes.json')
  const tuples = JSON.parse(readFileSync(path, 'utf8')) as SdeTuple[]
  types = tuples.map(([typeID, name, groupID, categoryID]) => ({ typeID, name, groupID, categoryID }))
  byID = new Map(types.map((t) => [t.typeID, t]))
  return types
}

export const getSdeType = (typeID: number): SdeType | null => {
  load()
  return byID?.get(typeID) ?? null
}

export const getSdeTypeNames = (typeIDs: Iterable<number>): Record<number, string> => {
  const result: Record<number, string> = {}
  for (const id of typeIDs) {
    const type = getSdeType(id)
    if (type) result[id] = type.name
  }
  return result
}

export type SdeSearchResult = { typeID: number; name: string; coverage: number }

// Case-insensitive substring search, ranked by how much of the name the query
// covers (a tighter match ranks above a longer name containing the same term).
export const searchSdeTypes = (query: string, limit = 25): SdeSearchResult[] => {
  const needle = query.trim().toLowerCase()
  if (needle === '') return []
  const results: SdeSearchResult[] = []
  for (const t of load()) {
    const idx = t.name.toLowerCase().indexOf(needle)
    if (idx === -1) continue
    results.push({ typeID: t.typeID, name: t.name, coverage: needle.length / t.name.length })
  }
  results.sort((a, b) => b.coverage - a.coverage || a.name.length - b.name.length)
  return results.slice(0, limit)
}
