// TypeScript enum + type-safe default columns for industry jobs exports.
// Ensures DEFAULT_COLUMNS is always a subset of ALLOWED_COLUMNS.

export const INDUSTRY_JOB_COLUMNS = {
  ACTIVITY_ID: 'activity_id',
  BLUEPRINT_ID: 'blueprint_id',
  BLUEPRINT_LOCATION_ID: 'blueprint_location_id',
  BLUEPRINT_TYPE_ID: 'blueprint_type_id',
  BLUEPRINT_TYPE_NAME: 'blueprint_type_name',
  COMPLETED_CHARACTER_ID: 'completed_character_id',
  COMPLETED_DATE: 'completed_date',
  CORPORATION_ID: 'corporation_id',
  COST: 'cost',
  DURATION: 'duration',
  END_DATE: 'end_date',
  FACILITY_ID: 'facility_id',
  INSTALLER_ID: 'installer_id',
  JOB_ID: 'job_id',
  LICENSED_RUNS: 'licensed_runs',
  OUTPUT_LOCATION_ID: 'output_location_id',
  PAUSE_DATE: 'pause_date',
  PROBABILITY: 'probability',
  PRODUCT_TYPE_ID: 'product_type_id',
  PRODUCT_TYPE_NAME: 'product_type_name',
  RUNS: 'runs',
  START_DATE: 'start_date',
  STATION_ID: 'station_id',
  STATUS: 'status',
  SUCCESSFUL_RUNS: 'successful_runs',
  CHARACTER_NAME: 'character_name',
} as const

export type IndustryJobColumn = (typeof INDUSTRY_JOB_COLUMNS)[keyof typeof INDUSTRY_JOB_COLUMNS]

export const CHARACTER_JOB_ALLOWED_COLUMNS = [
  INDUSTRY_JOB_COLUMNS.ACTIVITY_ID,
  INDUSTRY_JOB_COLUMNS.BLUEPRINT_ID,
  INDUSTRY_JOB_COLUMNS.BLUEPRINT_LOCATION_ID,
  INDUSTRY_JOB_COLUMNS.BLUEPRINT_TYPE_ID,
  INDUSTRY_JOB_COLUMNS.BLUEPRINT_TYPE_NAME,
  INDUSTRY_JOB_COLUMNS.COMPLETED_CHARACTER_ID,
  INDUSTRY_JOB_COLUMNS.COMPLETED_DATE,
  INDUSTRY_JOB_COLUMNS.COST,
  INDUSTRY_JOB_COLUMNS.DURATION,
  INDUSTRY_JOB_COLUMNS.END_DATE,
  INDUSTRY_JOB_COLUMNS.FACILITY_ID,
  INDUSTRY_JOB_COLUMNS.INSTALLER_ID,
  INDUSTRY_JOB_COLUMNS.JOB_ID,
  INDUSTRY_JOB_COLUMNS.LICENSED_RUNS,
  INDUSTRY_JOB_COLUMNS.OUTPUT_LOCATION_ID,
  INDUSTRY_JOB_COLUMNS.PAUSE_DATE,
  INDUSTRY_JOB_COLUMNS.PROBABILITY,
  INDUSTRY_JOB_COLUMNS.PRODUCT_TYPE_ID,
  INDUSTRY_JOB_COLUMNS.PRODUCT_TYPE_NAME,
  INDUSTRY_JOB_COLUMNS.RUNS,
  INDUSTRY_JOB_COLUMNS.START_DATE,
  INDUSTRY_JOB_COLUMNS.STATION_ID,
  INDUSTRY_JOB_COLUMNS.STATUS,
  INDUSTRY_JOB_COLUMNS.SUCCESSFUL_RUNS,
  INDUSTRY_JOB_COLUMNS.CHARACTER_NAME,
] as const

export const CORP_JOB_ALLOWED_COLUMNS = [
  INDUSTRY_JOB_COLUMNS.ACTIVITY_ID,
  INDUSTRY_JOB_COLUMNS.BLUEPRINT_ID,
  INDUSTRY_JOB_COLUMNS.BLUEPRINT_LOCATION_ID,
  INDUSTRY_JOB_COLUMNS.BLUEPRINT_TYPE_ID,
  INDUSTRY_JOB_COLUMNS.BLUEPRINT_TYPE_NAME,
  INDUSTRY_JOB_COLUMNS.COMPLETED_CHARACTER_ID,
  INDUSTRY_JOB_COLUMNS.COMPLETED_DATE,
  INDUSTRY_JOB_COLUMNS.CORPORATION_ID,
  INDUSTRY_JOB_COLUMNS.COST,
  INDUSTRY_JOB_COLUMNS.DURATION,
  INDUSTRY_JOB_COLUMNS.END_DATE,
  INDUSTRY_JOB_COLUMNS.FACILITY_ID,
  INDUSTRY_JOB_COLUMNS.INSTALLER_ID,
  INDUSTRY_JOB_COLUMNS.JOB_ID,
  INDUSTRY_JOB_COLUMNS.LICENSED_RUNS,
  INDUSTRY_JOB_COLUMNS.OUTPUT_LOCATION_ID,
  INDUSTRY_JOB_COLUMNS.PAUSE_DATE,
  INDUSTRY_JOB_COLUMNS.PROBABILITY,
  INDUSTRY_JOB_COLUMNS.PRODUCT_TYPE_ID,
  INDUSTRY_JOB_COLUMNS.PRODUCT_TYPE_NAME,
  INDUSTRY_JOB_COLUMNS.RUNS,
  INDUSTRY_JOB_COLUMNS.START_DATE,
  INDUSTRY_JOB_COLUMNS.STATION_ID,
  INDUSTRY_JOB_COLUMNS.STATUS,
  INDUSTRY_JOB_COLUMNS.SUCCESSFUL_RUNS,
  // Note: corp_industry_jobs doesn't include installer_name from ESI, only installer_id
] as const

// Type guard: ensures DefaultColumns is a subset of AllowedColumns
type ValidateSubset<T extends readonly unknown[], U extends readonly unknown[]> = T extends readonly (infer E)[]
  ? E extends U[number]
    ? T
    : never
  : never

// Character jobs defaults: exclude blueprint_type_name and product_type_name (SQL doesn't provide them)
export const CHARACTER_JOB_DEFAULT_COLUMNS = [
  INDUSTRY_JOB_COLUMNS.JOB_ID,
  INDUSTRY_JOB_COLUMNS.BLUEPRINT_TYPE_ID,
  INDUSTRY_JOB_COLUMNS.PRODUCT_TYPE_ID,
  INDUSTRY_JOB_COLUMNS.RUNS,
  INDUSTRY_JOB_COLUMNS.STATUS,
  INDUSTRY_JOB_COLUMNS.START_DATE,
  INDUSTRY_JOB_COLUMNS.END_DATE,
  INDUSTRY_JOB_COLUMNS.CHARACTER_NAME,
] as const satisfies ValidateSubset<typeof CHARACTER_JOB_DEFAULT_COLUMNS, typeof CHARACTER_JOB_ALLOWED_COLUMNS>

// Corp jobs defaults: no character_name (unlike character jobs)
export const CORP_JOB_DEFAULT_COLUMNS = [
  INDUSTRY_JOB_COLUMNS.JOB_ID,
  INDUSTRY_JOB_COLUMNS.BLUEPRINT_TYPE_ID,
  INDUSTRY_JOB_COLUMNS.PRODUCT_TYPE_ID,
  INDUSTRY_JOB_COLUMNS.RUNS,
  INDUSTRY_JOB_COLUMNS.STATUS,
  INDUSTRY_JOB_COLUMNS.START_DATE,
  INDUSTRY_JOB_COLUMNS.END_DATE,
  INDUSTRY_JOB_COLUMNS.CORPORATION_ID,
] as const satisfies ValidateSubset<typeof CORP_JOB_DEFAULT_COLUMNS, typeof CORP_JOB_ALLOWED_COLUMNS>
